services:
  employee-server:
    container_name: my_rest_app
    image: employeerest:latest
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
      - activemq
#    build:
#      context: ./
#      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    volumes:
      - employee-server-data:/app

  db:
    container_name: postgres_db
    depends_on:
      - activemq
    image: postgres:14.1-alpine
    restart: always
    secrets:
      - db-password
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: run/secrets/db-password
      POSTGRES_SCHEMA: public
      POSTGRES_DATABASE: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  activemq:
    image: webcenter/activemq:latest
    container_name: activemq
    ports:
      - 8161:8161
    volumes:
      - activemq-data:/opt/activemq/conf
      - activemq-data:/data/activemq
      - activemq-data:/var/log/activemq

volumes:
  db-data:
  activemq-data:
  employee-server-data:

secrets:
  db-password:
    file: db/password.txt